### PR TITLE
update to the latest version of lazyledger-core

### PR DESCRIPTION
**Pull request by evan-forbes**
## Description
lazyledger-core has just had some minor [dependency version bumps](https://github.com/lazyledger/lazyledger-core/pull/159#event-4349183815), so this PR updates the go.mod to the latest commit of the master branch. One of the updated dependencies is grpc `v1.35.0`, which causes a [weird marshaling bug](https://github.com/lazyledger/cosmos-sdk/issues/2), so to avoid the bug this PR also adds a replace directive to force the sdk to use `v1.33.2`.

closes: #XXXX

### CODE REVIEW

**Review by tzdybal — COMMENTED** [review]
So basically you're updating grpc and downgrading it back (with replace) at the same commit?

**Comment by liamsi** [comment]
Yes, see : https://github.com/lazyledger/lazyledger-core/pull/159#event-4349183815

**Review by liamsi — APPROVED** [review]
👍🏼 But we need to investigate the failing tests and appease the linter gods before merging.

**Comment by evan-forbes** [comment]
Weirdly enough, the app works fine when v1.35.0 is used, however it introduces non-deterministic test failures in some of the modules' integration tests in the sdk. Even weirder, the tests that fail seem to fail consistently per machine, but which tests fail change per machine. :man_shrugging: 


The test that was failing appeared to be [this](https://github.com/cosmos/cosmos-sdk/issues/1639). Re-running the CI fixes this.

The linter gods kindly never let us forget about the writing file permission issues that were discussed [here](https://github.com/lazyledger/cosmos-sdk/pull/13#issuecomment-764492044). That writing function in the `tmos` library, mentioned in the linked comment, is not recognized by the linter, so it doesn't complain. That function was deleted in one of the tendermint version updates to lazyledger-core, so it was replaced and now we live under constant scrutiny from the linter gods. 

I can make a new wrapper of ioutil to silence them, use different permissions, ignore the linter in this case, or we can remove the linter check somehow. Which sounds better?

**Comment by liamsi** [comment]
Hmm, the plan is to use the latest stable tendermint version in lazyledger-core (0.34.x) and the latest stable sdk release: https://github.com/cosmos/cosmos-sdk/tree/v0.41.x 

I think in both those version `os` package exists and is still used. TBH, I'm OK with ignoring those here (using a nolint directive). We should track this in an issue so we won't forget about it and we should also  open an issue on the SDK side as the perms look dodgy!

**Comment by liamsi** [comment]
Regarding the grpc story I trust Marko's call to replace it and also this seems to be the taken approach in the SDK.

**Comment by evan-forbes** [comment]
I can add the write function back to ll-core [here](https://github.com/lazyledger/lazyledger-core/blob/master/libs/os/os.go)

It's been removed in the [master](https://github.com/tendermint/tendermint/blob/master/libs/os/os.go) branch of tendermint, but is still [there](https://github.com/tendermint/tendermint/blob/dea73e08b3aa90377316dc66c5c181f9eb0b147a/libs/os/os.go#L74) in `v0.34.8`

**Comment by liamsi** [comment]
Let's figure out the whole write function story together with bringing lazyledger-core more on par with the 0.34.x branch. We need an issue for latter too. I thought I've already openened one but apparently not.

**Comment by evan-forbes** [comment]
I'm opening one now with all the context

**Pull request closed without merging**
